=== mgottschlag/kwin-tiling/kdm/kfrontend/themes/greeter.dtd
<!ELEMENT greeter (item | normal | style)+>	<!-- The root is an item of type "rect". -->
<!ELEMENT item (fixed | box | pos | normal | active | prelight | show | text | stock | color | style | buddy)*>
<!ELEMENT fixed (item+)>
<!ELEMENT box (item+)>
<!ELEMENT pos EMPTY>
<!ELEMENT show EMPTY>
<!ELEMENT text (#PCDATA)>
<!ELEMENT normal EMPTY>
<!ELEMENT active EMPTY>
<!ELEMENT prelight EMPTY>
<!ELEMENT stock EMPTY>
<!ELEMENT color EMPTY>
<!ELEMENT style EMPTY>
<!ELEMENT buddy EMPTY>

<!--
Items with these IDs get special treatment:
	xconsole | userlist |
	caps-lock-warning | xauth-warning | pam-error | timed-label |
	login_button | session_button | system_button
Items with these IDs might get special treatment by conversation plugins:
	talker | domain-entry | user-entry | pw-entry
Items with these IDs are always hidden:
	pam-message | language_button
-->

<!ATTLIST item
	type (rect | entry | pixmap | label | svg | list) #REQUIRED
	id CDATA #IMPLIED
	button (true | false) #IMPLIED
	background (true | false) #IMPLIED
>
<!ATTLIST pos
	x CDATA #IMPLIED
	y CDATA #IMPLIED
	anchor CDATA "c"
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	min-width CDATA #IMPLIED
	min-height CDATA #IMPLIED
	max-width CDATA #IMPLIED
	max-height CDATA #IMPLIED
	expand (true | false) #IMPLIED
>
<!ENTITY % colorattrs "
	file CDATA #IMPLIED
	element CDATA #IMPLIED
	color CDATA #IMPLIED
	font CDATA #IMPLIED
	tint CDATA #IMPLIED
	alpha CDATA #IMPLIED">
<!ATTLIST normal
	%colorattrs;
>
<!ATTLIST active
	%colorattrs;
>
<!ATTLIST prelight
	%colorattrs;
>
<!ATTLIST stock
	type (language | session | system | disconnect | quit | halt | reboot | chooser | caps-lock-warning | timed-label | welcome-label | username-label | domain-label | username-label | password-label | login) #REQUIRED
>
<!ATTLIST box
	orientation (horizontal | vertical) "horizontal"
	spacing CDATA #IMPLIED
	xpadding CDATA #IMPLIED
	ypadding CDATA #IMPLIED
	min-width CDATA #IMPLIED
	min-height CDATA #IMPLIED
	homogeneous (true | false) #IMPLIED
>
<!-- modes: (everywhere | nowhere | console | * ) -->
<!-- type: !? (config | chooser | system | halt | reboot | suspend | timed | plugin-*) -->
<!ATTLIST show
	modes CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!ATTLIST text
	xml:lang CDATA #IMPLIED
>
<!ATTLIST color
	labelcolor CDATA #IMPLIED
	altlabelcolor CDATA #IMPLIED
>
<!ATTLIST style
	font CDATA #IMPLIED
	edit-font CDATA #IMPLIED
	window-color CDATA #IMPLIED
	window-alpha CDATA #IMPLIED
	window-text-color CDATA #IMPLIED
	window-text-alpha CDATA #IMPLIED
	base-color CDATA #IMPLIED
	base-alpha CDATA #IMPLIED
	alternate-base-color CDATA #IMPLIED
	alternate-base-alpha CDATA #IMPLIED
	text-color CDATA #IMPLIED
	text-alpha CDATA #IMPLIED
	highlight-color CDATA #IMPLIED
	highlight-alpha CDATA #IMPLIED
	highlighted-text-color CDATA #IMPLIED
	highlighted-text-alpha CDATA #IMPLIED
	button-color CDATA #IMPLIED
	button-alpha CDATA #IMPLIED
	button-text-color CDATA #IMPLIED
	button-text-alpha CDATA #IMPLIED
	bright-text-color CDATA #IMPLIED
	bright-text-alpha CDATA #IMPLIED
	frame (true | false) #IMPLIED
>
<!ATTLIST buddy
	idref IDREF #REQUIRED
>

=== mgottschlag/kwin-tiling/kdm/kfrontend/themes/circles/circles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE greeter SYSTEM "greeter.dtd">
<greeter>
	<item type="rect" id="background">
		<pos x="0" y="0" height="100%" width="100%"/>
		<fixed>
			<item type="svg">
				<normal file="background.svg"/>
				<pos x="0" y="0" width="100%" height="-75"/>
			</item>
			<item type="rect">
				<normal color="#000000"/>
				<pos x="0" y="-75" width="100%" height="75"/>
				<fixed>
					<item type="rect">
						<normal color="#ffffff"/>
						<pos x="0" y="4" width="100%" height="100%"/>
					</item>
				</fixed>
			</item>
			<item type="pixmap">
				<normal file="flower.png"/>
				<pos x="100%" y="100%" anchor="se"/>
			</item>
		</fixed>
	</item>
	<item type="label" id="clock">
		<normal color="#000000" font="Sans 12"/>
		<pos x="-20" y="-37" anchor="e"/>
		<text>%c</text>
	</item>
	<item type="rect">
		<pos x="0" y="-75" width="100%" height="75"/>
		<fixed>
			<item type="rect">
				<pos x="0" y="4" width="100%" height="100%"/>
				<box orientation="horizontal" spacing="10" xpadding="10">
					<item type="rect" id="language_button" button="true">
						<normal color="#ffffff"/>
						<pos y="50%" anchor="w" width="box" height="box"/>
						<box orientation="horizontal" spacing="10" xpadding="10">
							<item type="pixmap">
								<normal file="options.png" tint="#dddddd"/>
								<prelight file="options.png"/>
								<active file="options.png" tint="#ff0000"/>
								<pos y="50%" anchor="w"/>
							</item>
							<item type="label">
								<normal color="#000000" font="Sans 12"/>
								<prelight color="#666666" font="Sans 12"/>
								<active color="#ff0000" font="Sans 12"/>
								<pos y="50%" anchor="w"/>
								<!-- Stock label for: _Language -->
								<stock type="language"/>
							</item>
						</box>
					</item>
					<item type="rect" id="session_button" button="true">
						<normal color="#ffffff"/>
						<pos y="50%" anchor="w" width="box" height="box"/>
						<box orientation="horizontal" spacing="10" xpadding="10">
							<item type="pixmap">
								<normal file="help.png" tint="#dddddd"/>
								<prelight file="help.png"/>
								<active file="help.png" tint="#ff0000"/>
								<pos y="50%" anchor="w"/>
							</item>
							<item type="label">
								<normal color="#000000" font="Sans 12"/>
								<prelight color="#666666" font="Sans 12"/>
								<active color="#ff0000" font="Sans 12"/>
								<pos y="50%" anchor="w"/>
								<!-- Stock label for: _Session -->
								<stock type="session"/>
							</item>
						</box>
					</item>
					<item type="rect" id="system_button" button="true">
						<normal color="#ffffff"/>
						<show modes="console" type="system"/>
						<pos y="50%" anchor="w" width="box" height="box"/>
						<box orientation="horizontal" spacing="10" xpadding="10">
							<item type="pixmap">
								<normal file="options.png" tint="#dddddd"/>
								<prelight file="options.png"/>
								<active file="options.png" tint="#ff0000"/>
								<pos y="50%" anchor="w"/>
							</item>
							<item type="label">
								<normal color="#000000" font="Sans 12"/>
								<prelight color="#666666" font="Sans 12"/>
								<active color="#ff0000" font="Sans 12"/>
								<pos y="50%" anchor="w"/>
								<!-- Stock label for: _Actions -->
								<stock type="system"/>
							</item>
						</box>
					</item>
					<item type="rect" id="disconnect_button" button="true">
						<normal color="#ffffff"/>
						<show modes="flexi,remote"/>
						<pos y="50%" anchor="w" width="box" height="box"/>
						<box orientation="horizontal" spacing="10" xpadding="10">
							<item type="pixmap">
								<normal file="options.png" tint="#dddddd"/>
								<prelight file="options.png"/>
								<active file="options.png" tint="#ff0000"/>
								<pos y="50%" anchor="w"/>
							</item>
							<item type="label">
								<normal color="#000000" font="Sans 12"/>
								<prelight color="#666666" font="Sans 12"/>
								<active color="#ff0000" font="Sans 12"/>
								<pos y="50%" anchor="w"/>
								<!-- Stock label for: D_isconnect -->
								<stock type="disconnect"/>
								<show modes="remote"/>
							</item>
							<item type="label">
								<normal color="#000000" font="Sans 12"/>
								<prelight color="#666666" font="Sans 12"/>
								<active color="#ff0000" font="Sans 12"/>
								<pos y="50%" anchor="w"/>
								<!-- Stock label for: _Quit -->
								<stock type="quit"/>
								<show modes="flexi"/>
							</item>
						</box>
					</item>
				</box>
			</item>
		</fixed>
	</item>
	<item type="rect" id="timed-label">
		<show type="timed"/>
		<normal color="#FFFFFF" alpha="0.5"/>
		<pos anchor="c" x="50%" y="20%" width="box" height="box"/>
		<box orientation="vertical" xpadding="50" ypadding="5" spacing="0">
			<item type="label">
				<normal color="#000000" font="Sans 12"/>
				<pos x="50%" anchor="n"/>
				<!-- Stock label for: User %s will login in %d seconds -->
				<stock type="timed-label"/>
			</item>
		</box>
	</item>
	<item type="rect" id="greeter">
		<pos anchor="c" x="50%" y="50%" width="box" height="1"/>
		<box orientation="horizontal" xpadding="0" ypadding="0" spacing="20">
			<item type="list" id="userlist">
				<color labelcolor="#40c0c0c0" altlabelcolor="#40e0e0e0"/>
				<pos anchor="w" max-height="50%^"/>
			</item>
			<item type="rect" id="verify">
				<normal color="#FFFFFF" alpha="0.5"/>
				<pos anchor="w" width="box" height="box"/>
				<box orientation="vertical" min-width="340" xpadding="30" ypadding="30" spacing="10">
					<item type="label">
						<pos anchor="n" x="50%"/>
						<normal color="#000000" font="Sans 14"/>
						<!-- Stock label for: Welcome to %h -->
						<stock type="welcome-label"/>
					</item>
					<item type="rect" id="talker">
						<normal color="#0" alpha="0"/>
						<pos anchor="n" x="50%" width="box" height="box"/>
						<!-- box orientation="vertical" xpadding="0" ypadding="0" spacing="10" -->
						<box orientation="horizontal" xpadding="0" ypadding="0" spacing="0">
							<item type="rect">
								<normal color="#FF8080" alpha="0.0"/>
								<pos anchor="w" y="50%" width="box" height="box"/>
								<box orientation="vertical" xpadding="0" ypadding="0" spacing="14">
									<item type="label">
										<buddy idref="user-entry"/>
										<pos anchor="ne" x="100%"/>
										<normal color="#000000" font="Sans 12"/>
										<!-- Stock label for: Username: -->
										<stock type="username-label"/>
									</item>
									<item type="label">
										<buddy idref="pw-entry"/>
										<pos anchor="ne" x="100%"/>
										<normal color="#000000" font="Sans 12"/>
										<!-- Stock label for: Password: -->
										<stock type="password-label"/>
									</item>
								</box>
							</item>
							<item type="rect">
								<normal color="#FF80FF" alpha="0.0"/>
								<pos anchor="w" y="50%" width="box" height="box"/>
								<box orientation="vertical" xpadding="0" ypadding="0" spacing="10">
									<item type="entry" id="user-entry">
										<pos anchor="n" x="50%" height="24" width="150"/>
									</item>
									<item type="entry" id="pw-entry">
										<pos anchor="n" x="50%" height="24" width="150"/>
									</item>
								</box>
							</item>
						</box>
					</item>
				</box>
				<fixed>
					<item type="label" id="pam-error">
						<pos anchor="n" x="50%" y="85%"/>
						<normal color="#000000" font="Sans Bold 12"/>
						<text/>
					</item>
					<item type="rect" id="caps-lock-warning">
						<normal color="#FFFFFF" alpha="0.5"/>
						<pos anchor="n" x="50%" y="125%" width="box" height="box"/>
						<box orientation="vertical" xpadding="50" ypadding="5" spacing="0">
							<item type="label">
								<normal color="#ff0000" font="Sans 12"/>
								<pos x="50%" anchor="n"/>
								<!-- Stock label for: You've got capslock on! -->
								<stock type="caps-lock-warning"/>
							</item>
						</box>
					</item>
				</fixed>
			</item>
		</box>
	</item>
</greeter>

=== mgottschlag/kwin-tiling/kdm/kfrontend/themes/oxygen/oxygen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE greeter SYSTEM "greeter.dtd">
<!--
Copyright 2008 Urs Wolfer <uwolfer @ kde.org>
Copyright 2008 Oswald Buddenhagen <ossi @ kde.org>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of 
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<greeter id="theme">
	<style font="Sans 12" window-text-color="#C7C7C7"
	       base-color="#C7C7C7" alternate-base-color="#666666"
	       text-color="#000000" disabled-text-color="#808080"/>
	<item type="svg" id="background" background="true">
		<normal file="background.svg"/>
		<pos anchor="c" x="50%" y="50%" width="scale" height="100%"/>
	</item>

	<item type="rect" id="greeter">
		<pos y="50%" x="50%" anchor="c" width="box" height="box"/>

		<fixed>
			<item type="svg">
				<normal file="oxygen-box.svg" element="topleft"/>
				<pos anchor="nw" x="0" y="0" width="11" height="11"/>
			</item>
			<item type="svg">
				<normal file="oxygen-box.svg" element="top"/>
				<pos anchor="n" x="50%" y="0" width="-21" height="11"/>
			</item>
			<item type="svg">
				<normal file="oxygen-box.svg" element="topright"/>
				<pos anchor="ne" x="-0" y="0" width="11" height="11"/>
			</item>
			<item type="svg">
				<normal file="oxygen-box.svg" element="left"/>
				<pos anchor="w" x="0" y="50%" width="11" height="-21"/>
			</item>
			<item type="svg">
				<normal file="oxygen-box.svg" element="center"/>
				<pos anchor="c" x="50%" y="50%" width="-21" height="-21"/>
			</item>
			<item type="svg">
				<normal file="oxygen-box.svg" element="right"/>
				<pos anchor="e" x="-0" y="50%" width="11" height="-21"/>
			</item>
			<item type="svg">
				<normal file="oxygen-box.svg" element="bottomleft"/>
				<pos anchor="sw" x="0" y="-0" width="11" height="11"/>
			</item>
			<item type="svg">
				<normal file="oxygen-box.svg" element="bottom"/>
				<pos anchor="s" x="50%" y="-0" width="-21" height="11"/>
			</item>
			<item type="svg">
				<normal file="oxygen-box.svg" element="bottomright"/>
				<pos anchor="se" x="-0" y="-0" width="11" height="11"/>
			</item>
		</fixed>

		<box orientation="vertical" xpadding="15" ypadding="15" spacing="10">
			<item type="rect" id="banner">
				<pos width="box" height="box" min-width="100%"/>
				<box orientation="horizontal" spacing="10">
					<item type="label" id="welcome">
						<pos anchor="w" y="50%"/>
						<normal color="#8BAFBA" font="Sans 16"/>
						<stock type="welcome-label"/>
					</item>
					<item type="rect" id="spacer1">
						<pos expand="true"/>
					</item>
					<item type="pixmap" id="branding">
						<normal file="branding-icon.png"/>
					</item>
				</box>
			</item>
			<item type="rect" id="content">
				<pos width="box" height="box"/>
				<box orientation="horizontal" spacing="10">
					<item type="list" id="userlist">
						<pos max-height="30%^^"/>
					</item>
					<item type="rect" id="verify">
						<pos width="box" height="box"/>
						<box orientation="vertical" spacing="2">
							<item type="rect" id="talker">
								<pos anchor="n" x="50%" width="box" height="box"/>
								<box orientation="vertical" xpadding="2" ypadding="2" spacing="2">
									<item type="label">
										<pos x="5"/>
										<stock type="username-label"/>
									</item>
									<item type="entry" id="user-entry">
										<pos width="150" height="22"/>
									</item>
									<item type="label">
										<pos x="5"/>
										<stock type="password-label"/>
									</item>
									<item type="entry" id="pw-entry">
										<pos width="150" height="22"/>
									</item>
								</box>
							</item>
							<item type="rect" id="pam-error-placeholder">
								<pos width="100%" height="box"/>
								<box orientation="horizontal">
									<item type="label" id="dummy1">
										<normal alpha="0" font="Sans Bold 12"/>
										<text/>
									</item>
									<item type="label" id="pam-error">
										<pos anchor="c" x="50%" y="50%" expand="true"/>
										<normal color="#C7C7C7" font="Sans Bold 12"/>
										<text/>
									</item>
								</box>
							</item>
							<item type="label" id="caps-lock-warning">
								<normal color="#C7C7C7" font="Sans 12"/>
								<pos anchor="c" x="50%" y="50%"/>
								<stock type="caps-lock-warning"/>
							</item>
						</box>
					</item>
				</box>
			</item>
		</box>

	</item>

	<!-- bottom bar and session buttons -->
	<item type="rect" id="footer">
		<pos x="-0" y="-75" min-width="50%" width="box" height="43" anchor="e"/>
		<fixed>
			<item type="svg">
				<normal file="oxygen.svg" element="footer-background"/>
				<pos width="1980" height="43"/>
			</item>
		</fixed>
		<box orientation="horizontal" spacing="10" xpadding="10">
			<item type="rect" id="session_button" button="true">
				<pos y="50%" anchor="w" width="box" height="box"/>
				<box orientation="horizontal" spacing="10" xpadding="10">
					<item type="pixmap">
						<normal file="session.png" tint="#ffffff"/>
						<prelight file="session.png"/>
						<active file="session.png" tint="#ffffff"/>
						<pos y="50%" anchor="w"/>
					</item>
					<item type="label">
						<normal color="#C7C7C7" font="Sans 12"/>
						<prelight color="#ffffff" font="Sans 12"/>
						<active color="#666666" font="Sans 12"/>
						<pos y="50%" anchor="w"/>
						<stock type="session"/>
					</item>
				</box>
			</item>
			<item type="rect" id="system_button" button="true">
				<show modes="console" type="system"/>
				<pos y="50%" anchor="w" width="box" height="box"/>
				<box orientation="horizontal" spacing="10" xpadding="10">
					<item type="pixmap">
						<normal file="system.png" tint="#ffffff"/>
						<prelight file="system.png"/>
						<active file="system.png" tint="#ffffff"/>
						<pos y="50%" anchor="w"/>
					</item>
					<item type="label">
						<normal color="#C7C7C7" font="Sans 12"/>
						<prelight color="#ffffff" font="Sans 12"/>
						<active color="#666666" font="Sans 12"/>
						<pos y="50%" anchor="w"/>
						<stock type="system"/>
					</item>
				</box>
			</item>
			<item type="rect" id="spacer2">
				<pos expand="true"/>
			</item>
			<item type="label" id="clock">
				<pos anchor="w" y="50%"/>
				<normal font="Sans 12" color="#C7C7C7"/>
				<text>%c</text>
			</item>
			<item type="rect" id="spacer3">
				<pos width="15"/>
			</item>
		</box>
	</item>

	<item type="rect" id="timed-label">
		<pos anchor="c" x="50%" y="20%" width="box" height="box"/>
		<box orientation="vertical" xpadding="50" ypadding="5" spacing="0">
			<item type="label">
				<normal color="#C7C7C7" font="Sans 12"/>
				<pos x="50%" anchor="n"/>
				<stock type="timed-label"/>
			</item>
		</box>
	</item>

</greeter>

=== mgottschlag/kwin-tiling/kdm/kfrontend/themes/oxygen-air/oxygen-air.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE greeter SYSTEM "greeter.dtd">

<greeter id="theme">
	<style font="Sans 12" window-text-color="#bfd9ff"
	       base-color="#bfd9ff" alternate-base-color="#666666"
	       text-color="#0b678c" disabled-text-color="#111111"/>
	       
	<item type="pixmap" id="background" background="true">
		<normal file="1280x800.jpg"/>
		<pos anchor="c" x="50%" y="50%" width="scale" height="100%"/>
	</item>

	<item type="pixmap" id="system-session">
		<normal file="win-login.png"/>
		<pos anchor="c" x="50%" y="45%" width="615" height="401"/>
		<box orientation="vertical" spacing="10" homogeneous="true">
		
			<item type="pixmap">
				<normal file="icon-kde.png"/>
				<pos anchor="c" x="50%" y="80%"/>
			</item>

			<item type="label" id="welcome">
				<pos anchor="c" x="50%" y="46%"/>
				<normal alpha="0.5" font="Sans Bold 18" color="#FFFFFF"/>
				<stock type="welcome-label"/>
			</item>

			<item type="rect" id="user-field">
				<pos anchor="c" x="50%" y="43%" width="400" height="144"/>
				<box orientation="vertical" spacing="0" homogeneous="true">
				
					<item type="pixmap" butoon="true">
						<normal file="user-entry.png"/>
						<prelight file="user-entry-li.png"/>
						<active file="user-entry-li.png"/>
						<pos anchor="c" x="50%" y="100%"/>
					</item>
					
					<item type="entry" id="user-entry">
						<pos anchor="c" x="52%" y="0%" width="110" height="22"/>
					</item>

					<item type="pixmap">
						<normal file="pw-entry.png"/>
						<prelight file="pw-entry-li.png"/>
						<pos anchor="c" x="50%" y="100%"/>
					</item>
									
					<item type="entry" id="pw-entry">
						<pos anchor="c" x="52%" y="0%" width="110" height="22"/>
					</item>
					
				</box>
			</item>
			
			<item type="rect" id="system-session">
			<pos anchor="c" x="50%" y="70%" width="615" height="44"/>
				<fixed>
			
					<item type="label">
						<pos anchor="se" x="96%" y="70%"/>
						<normal alpha="0.5" font="Sans 8" color="#ffffff"/>
						<text>%c</text>
					</item>			

					<item type="pixmap" id="session_button" button="true">
						<normal file="session_button.png"/>
						 <prelight file="session_button-li.png"/>
						<active file="session_button-li.png"/>
						<pos anchor="w" x="15" y="50%"/>
					</item>

					<item type="pixmap" id="system_button" button="true">
						<normal file="system_button.png"/>
						<prelight file="system_button-li.png"/>
						<active file="system_button-li.png"/>
						<pos anchor="w" x="47" y="50%"/>
					</item>

				</fixed>
		
			</item>
		</box>
	</item> 

	<item type="pixmap" id="caps-lock-warning">
	<normal file="caps.png"/>
	<pos anchor="c" x="50%" y="45%"/>
	
		<fixed>
		
			<item type="label" id="mesage">
			<normal color="#0b678c" font="Sans Bold 10"/>
			<pos anchor="c" x="50%" y="85%"/>
			<stock type="caps-lock-warning"/>
			</item>
			
		</fixed>
		
	</item>

	<item type="rect" id="pam-error-paceholder">
	<pos anchor="c" x="50%" y="98%" widht="615" height="200"/>

		<item type="label" id="dummy1">
			<normal alpha="0" color="#0b678c" font="Sans Bold 10"/>
			<!-- </text> -->
		</item>
		
		<item type="label" id="pam-error">
			<pos anchor="c" x="50%" y="50%" expand="true"/>
			<normal alpha="0" color="#0b678c" font="Sans Bold 10"/>
			<!-- </text> -->
		</item>

	</item>

</greeter>
